[[plugins]]
repo = 'lambdalisue/fern.vim'
on_cmd = 'Fern'
hook_add = '''
nmap <Leader>e <Cmd>Fern . -drawer -reveal=%<CR>
'''
hook_source = '''
let g:fern#hide_cursor = v:true
let g:fern#keepalt_on_edit = v:false
let g:fern#keepjumps_on_edit = v:false
let g:fern#default_hidden = v:true
let g:fern#disable_default_mappings = v:true
'''

[plugins.ftplugin]
fern = '''
wincmd =
nmap <nowait><buffer> <Space> <Plug>(fern-action-mark:toggle)
nmap <nowait><buffer> <C-l>   <Plug>(fern-action-reload:all)
nmap <nowait><buffer> h       <Plug>(fern-action-collapse)
nmap <nowait><buffer><expr> l fern#smart#leaf('<Plug>(fern-action-open)', '<Plug>(fern-action-expand)')
nmap <nowait><buffer> <Enter> <Plug>(fern-action-open)
nmap <nowait><buffer> y       <Plug>(fern-action-yank:path)
nmap <nowait><buffer> <C-c>   <Plug>(fern-action-cancel)
nmap <nowait><buffer> n       <Plug>(fern-action-new-file)
nmap <nowait><buffer> N       <Plug>(fern-action-new-dir)
nmap <nowait><buffer> d       <Plug>(fern-action-trash)
nmap <nowait><buffer> g       <Plug>(fern-action-grep)
nmap <nowait><buffer> r       <Plug>(fern-action-rename)
nmap <nowait><buffer> q       <Cmd>Fern . -drawer -toggle<CR>
'''

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
on_if = 'isdirectory(vimrc#get_buffer_path())'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
depends = 'nerdfont.vim'
on_source = 'fern.vim'
hook_add = '''
let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = 'fern.vim'
hook_source = '''
call fern_git_status#init()
'''

[[plugins]]
repo = 'lambdalisue/fern-mapping-git.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
on_source = 'fern.vim'

[plugins.ftplugin]
fern = '''
nmap <buffer> p     <Plug>(fern-action-preview:toggle)
nmap <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
nmap <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
nmap <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
'''
