[ftplugin]

html = '''
setlocal shiftwidth=2
setlocal tabstop=2
'''

toml = '''
setlocal shiftwidth=2
setlocal tabstop=2
setlocal keywordprg=:help
'''

typescript = '''
setlocal shiftwidth=2
setlocal tabstop=2
'''

vim = '''
setlocal shiftwidth=2
setlocal tabstop=2
'''

yaml = '''
setlocal shiftwidth=2
setlocal tabstop=2
'''

lua = '''
setlocal shiftwidth=2
setlocal tabstop=2
'''

qf = '''
let b:window_created = v:false
nmap <buffer><expr> <CR> b:window_created ? '<Enter>' : '<Cmd>let b:window_created=v:true<CR><C-w><Enter>'
'''
