[[plugins]]
repo = 'rhysd/committia.vim'
on_path = ['COMMIT_EDITMSG', 'MERGE_MSG']
hook_add = '''
augroup GitSpellCheck
    autocmd!
    autocmd FileType gitcommit setlocal spell
augroup END

let g:committia_hooks = {}
function! g:committia_hooks.edit_open(info)
    setlocal spell
    setlocal spelllang+=cjk
endfunction

let g:committia_open_only_vim_starting = 1
let g:committia_use_singlecolumn = 'fallback'
let g:committia_min_window_size = 160
let g:committia_status_window_opencmd = 'belowright split'
let g:committia_diff_window_opencmd = 'botright vsplit'
let g:committia_singlecolumn_diff_window_opencmd = 'belowright split'
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
on_func = 'gina#'
hook_add = '''
nmap <Leader>aA <Cmd>Gina changes HEAD<CR>
nmap <Leader>ac <Cmd>Gina commit<CR>
nmap <Leader>aC <Cmd>Gina commit --amend<CR>
nmap <Leader>at <Cmd>Gina tag<CR>
nmap <Leader>ag <Cmd>Gina grep<CR>
nmap <Leader>aq <Cmd>Gina qrep<CR>
nmap <Leader>ad <Cmd>Gina changes origin/HEAD...<CR>
nmap <Leader>ah <Cmd>execute printf('Gina log --graph %s', expand('%'))<CR>
nmap <Leader>aH <Cmd>Gina log --graph --all<CR>
nmap <Leader>af <Cmd>Gina ls<CR>
'''
hook_source = '''
call gina#custom#command#option(
    \ 'commit', '-v|--verbose'
    \ )
'''

[plugins.ftplugin]
gina-commit = '''
setlocal spell
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'
on_cmd = ['Gin', 'GinBranch', 'GinChaperon', 'GinDiff', 'GinEdit', 'GinPatch', 'GinStatus']
hook_add = '''
nmap <Leader>aa <Cmd>GinStatus<CR>
nmap <Leader>ab <Cmd>GinBranch<CR>
'''

[[plugins]]
repo = 'rhysd/git-messenger.vim'
on_cmd = 'GitMessenger'
on_map = { n = '<Plug>(git-messenger)' }
hook_add = '''
let g:git_messenger_no_default_mappings = v:true
nmap <Leader>mp <Plug>(git-messenger)
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
if = 'has("nvim")'
on_event = 'BufReadPost'
hook_add = '''
set signcolumn=yes
'''
hook_source = '''
lua require('local.config.plugins.gitsigns').setup()
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'
on_func = 'gitbranch#name'
