[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'vim-jp/vital.vim'
on_cmd = 'Vitalize'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
on_func = 'nerdfont#'

[[plugins]]
repo = 'onsails/lspkind-nvim'
on_lua = 'lspkind'
