[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = """
call lexima#add_rule({'char': '<C-]>', 'at': '\%#)', 'leave': 1})
call lexima#add_rule({'char': '<C-]>', 'at': '\%#"', 'leave': 1})
call lexima#add_rule({'char': '<C-]>', 'at': '\%#''', 'leave': 1})
call lexima#add_rule({'char': '<C-]>', 'at': '\%#]', 'leave': 1})
call lexima#add_rule({'char': '<C-]>', 'at': '\%#}', 'leave': 1})
"""

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
merged = 0
hook_source = '''
set helplang=ja,en
'''

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'hrsh7th/vim-searchx'
hook_source = '''
nnoremap / <Cmd>call searchx#start({ 'dir': 1 })<CR>
xnoremap / <Cmd>call searchx#start({ 'dir': 1 })<CR>
cnoremap ; <Cmd>call searchx#select()<CR>

nnoremap N <Cmd>call searchx#prev_dir()<CR>
nnoremap n <Cmd>call searchx#next_dir()<CR>
xnoremap N <Cmd>call searchx#prev_dir()<CR>
xnoremap n <Cmd>call searchx#next_dir()<CR>

nnoremap <Esc><Esc> <Cmd>call searchx#clear()<CR>

let g:searchx = {}
" auto jump if the recent input matches to any marker.
let g:searchx.auto_accept = v:true
" The scrolloff value for moving to next/prev.
let g:searchx.scrolloff = &scrolloff
" To diable scrolling animation.
let g:searchx.scrolltime = 0
" To enable auto nohlsearch after cursor is moved
let g:searchx.nohlsearch = {}
let g:searchx.nohlsearch.jump = v:true
" Marker characters.
let g:searchx.markers = split('ABCDEFGHIJKLMNOPQRSTUVWXYZ', '.\zs')
" Convert searchx pattern.
function g:searchx.convert(input) abort
    if a:input !~# '\k'
        return '\V' .. a:input
    endif
    return a:input[0] .. substitute(a:input[1:], '\\\@<! ', '.\\{-}', 'g')
endfunction
'''
