[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'lewis6991/impatient.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
merged = false
hook_add = '''
set helplang=ja,en
'''

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
nmap s <Nop>
xmap s <Nop>
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
