[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
merged = 0
hook_add = '''
set helplang=ja,en
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
nmap s <Nop>
xmap s <Nop>
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
