[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
nmap <Plug>(ddu-ff-dein)
      \ <Cmd>Ddu dein
        \ -ui-param-startFilter<CR>
'''

[[plugins]]
repo = 'lewis6991/impatient.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
merged = false
hook_add = '''
set helplang=ja,en
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
