[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
nmap <Plug>(ddu-ff-dein)
      \ <Cmd>Ddu dein
        \ -ui-param-startFilter<CR>
'''

[[plugins]]
repo = 'lewis6991/impatient.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
merged = false
hook_add = '''
set helplang=ja,en
'''

[[plugins]]
repo = 'andymass/vim-matchup'
hook_add = '''
let g:loaded_matchit = 1
let g:loaded_matchparen = 1
let g:matchup_matchparen_offscreen = {
      \ 'method': 'status_manual'
      \ }
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
