[[plugins]]
repo = 'hrsh7th/nvim-cmp'
name = 'cmp'
if = 'g:vimrc#use_cmp'
on_event = ['InsertEnter', 'CmdlineEnter']
hook_source = '''
lua << EOF
local cmp = require('cmp')

cmp.setup({
  window = {
    completion = {
      -- border = 'single',
    },
    documentation = {
      -- border = 'single',
    },
  },
  formatting = {
    fields = { 'kind', 'abbr', 'menu', },
    format = require("lspkind").cmp_format({
      with_text = false,
    })
  },
  mapping = {
    ['<C-n>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i' }),
    ['<C-p>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i' }),
    ['<Tab>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'c' }),
    ['<S-Tab>'] = cmp.mapping(cmp.mapping.select_prev_item(), { 'c' }),
    ['<C-d>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
    ['<C-u>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
    ['<C-e>'] = cmp.mapping({
      i = cmp.mapping.abort(),
      c = cmp.mapping.close(),
    }),
    ['<C-y>'] = cmp.mapping.confirm({ select = true, behavior = cmp.ConfirmBehavior.Replace }),
  },
  sources = cmp.config.sources({
    { name = 'nvim_lsp_signature_help' },
  }, {
    { name = 'path' },
  }, {
    { name = 'nvim_lsp' },
  }, {
    { name = 'calc' },
    { name = 'emoji' },
  }, {
    { name = 'buffer' },
  })
})
cmp.setup.filetype('gitcommit', {
  sources = require('cmp').config.sources({
    { name = 'cmp_git' },
  }, {
    { name = 'buffer' },
  })
})
require('cmp_git').setup({})
cmp.setup.cmdline(':', {
  sources = cmp.config.sources({
    { name = 'path' },
  }, {
    { name = 'cmdline' }
  }),
})
EOF
'''

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-document-symbol'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-signature-help'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-calc'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-emoji'
on_source = 'cmp'

[[plugins]]
repo = 'petertriho/cmp-git'
depends = 'plenary.nvim'
on_source = 'cmp'

[[plugins]]
repo = 'onsails/lspkind-nvim'
on_source = 'cmp'
