[[plugins]]
repo = 'hrsh7th/nvim-cmp'
name = 'cmp'
if = 'g:vimrc#use_cmp'
on_event = ['InsertEnter', 'CmdlineEnter']
hook_source = '''
" ./../lua/local/config/plugins/nvim-cmp.lua
lua require('local.config.plugins.nvim-cmp').setup()
'''

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-document-symbol'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-signature-help'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-calc'
on_source = 'cmp'

[[plugins]]
repo = 'hrsh7th/cmp-emoji'
on_source = 'cmp'

[[plugins]]
repo = 'petertriho/cmp-git'
depends = 'plenary.nvim'
on_source = 'cmp'
