[[plugins]]
repo = 'rebelot/kanagawa.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'iceberg'})
autocmd ColorSchemePre iceberg call vimrc#colorscheme#icebergPre()
'''

[[plugins]]
repo = 'savq/melange'

[[plugins]]
repo = '4513ECHO/vim-colors-hatsunemiku'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'gruvbox-material'})
autocmd ColorSchemePre gruvbox-material call vimrc#colorscheme#gruvboxMaterialPre()
'''

[[plugins]]
repo = 'ishan9299/nvim-solarized-lua'
if = 'has("nvim")'

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'edge'})
autocmd ColorSchemePre edge call vimrc#colorscheme#edgePre()
'''

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'everforest'})
autocmd ColorSchemePre everforest call vimrc#colorscheme#everforestPre()
'''

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'sonokai'})
autocmd ColorSchemePre sonokai call vimrc#colorscheme#sonokaiPre()
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
execute printf('colorscheme %s', vimrc#pick_random_colorscheme(g:vimrc#colorschemes)['name'])

call vimrc#lightline#setup()
'''
