[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_source = '''
lua << EOF
local nightfox = require('nightfox')
nightfox.setup({
    fox = "nordfox",
    transparent = true,
    styles = {
        comments = "italic",
        keywords = "bold",
        functions = "italic,bold"
    },
    inverse = {
        match_paren = true,
    },
    colors = {
        red = "#FF000",
        bg_alt = "#000000",
    },
    hlgroups = {
        TSPunctDelimiter = { fg = "${red}" },
        LspCodeLens = { bg = "#000000", style = "italic" },
    }
})
EOF
'''

[[plugins]]
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
    \ 'active': {
    \   'left': [ [ 'mode',  'paste' ],
    \       [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'FugitiveHead',
    \   'fileformat': 'LightLineFileFormat',
    \   'filetype': 'LightLineFileType',
    \ },
    \ }
let g:lightline.tabline = {
    \ 'left': [ [ 'tabs' ] ],
    \ 'right': [ [ 'close' ] ] }
if dein#tap('nightfox.nvim')
    let g:lightline.colorscheme = 'nightfox'
endif
function! LightLineFileFormat()
    return winwidth(0) > 70 ? &fileformat : ''
endfunction
function! LightLineFileType()
    return winwidth(0) > 70 ? &filetype : ''
endfunction
'''
