[[plugins]]
repo = 'rebelot/kanagawa.nvim'
hook_add = '''
call add(g:colorschemes, {'name': 'kanagawa'})
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:colorschemes, {'name': 'iceberg', 'background': 'dark'})
call add(g:colorschemes, {'name': 'iceberg', 'background': 'light'})
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
call add(g:colorschemes, {'name': 'hybrid', 'background': 'dark'})
'''

[[plugins]]
repo = 'https://gitlab.com/yorickpeterse/happy_hacking.vim'
hook_add = '''
call add(g:colorschemes, {'name': 'happy_hacking'})
'''

[[plugins]]
repo = 'savq/melange'
hook_add = '''
call add(g:colorschemes, {'name': 'melange', 'background': 'dark'})
call add(g:colorschemes, {'name': 'melange', 'background': 'light'})
'''

[[plugins]]
repo = '4513ECHO/vim-colors-hatsunemiku'
hook_add = '''
call add(g:colorschemes, {'name': 'hatsunemiku'})
call add(g:colorschemes, {'name': 'hatsunemiku_light'})
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
call add(g:colorschemes, {'name': 'gruvbox-material', 'background': 'dark'})
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = 'nvim-web-devicons'
if = 'has("nvim")'
lazy = 1
on_event = 'VimEnter'
hook_source = '''
call init#set_random_colorschme()
lua << EOF
require('lualine').setup()
EOF
'''
