[[plugins]]
repo = 'rebelot/kanagawa.nvim'
if = 'has("nvim")'
hook_add = '''
call add(g:colorschemes, {'name': 'kanagawa'})
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:colorschemes, {'name': 'iceberg', 'background': 'dark'})
call add(g:colorschemes, {'name': 'iceberg', 'background': 'light'})
'''

[[plugins]]
repo = 'savq/melange'

[[plugins]]
repo = '4513ECHO/vim-colors-hatsunemiku'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
call add(g:colorschemes, {'name': 'gruvbox-material', 'background': 'dark'})
'''

[[plugins]]
repo = 'ishan9299/nvim-solarized-lua'
if = 'has("nvim")'
hook_add = '''
call add(g:colorschemes, {'name': 'solarized', 'background': 'dark'})
call add(g:colorschemes, {'name': 'solarized', 'background': 'light'})
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = 'nvim-web-devicons'
if = 'has("nvim")'
lazy = 1
on_event = 'VimEnter'
hook_source = '''
call init#set_random_colorschme()
lua << EOF
require('lualine').setup()
EOF
'''
