[[plugins]]
repo = 'rebelot/kanagawa.nvim'
hook_add = '''
call add(g:colorschemes, {'name': 'kanagawa', 'background': 'dark'})
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:colorschemes, {'name': 'iceberg', 'background': 'dark'})
call add(g:colorschemes, {'name': 'iceberg', 'background': 'light'})
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
call add(g:colorschemes, {'name': 'hybrid', 'background': 'dark'})
'''

[[plugins]]
repo = 'YorickPeterse/vim-paper'
hook_add = '''
call add(g:colorschemes, {'name': 'paper', 'background': 'light'})
'''

[[plugins]]
repo = 'savq/melange'
hook_add = '''
call add(g:colorschemes, {'name': 'melange', 'background': 'dark'})
call add(g:colorschemes, {'name': 'melange', 'background': 'light'})
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
lazy = 1
on_event = 'VimEnter'
hook_add = '''
call init#set_random_colorschme()
'''
hook_source = '''
lua << EOF
require('lualine').setup()
EOF
'''
