[[plugins]]
repo = 'rebelot/kanagawa.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call vimrc#colorscheme#register('iceberg')
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
call vimrc#colorscheme#register('gruvbox-material')
'''

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
call vimrc#colorscheme#register('edge')
'''

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
call vimrc#colorscheme#register('everforest')
'''

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = '''
call vimrc#colorscheme#register('sonokai')
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
call vimrc#colorscheme#set_atrandom()
call vimrc#lightline#setup()
'''
