[[plugins]]
repo = 'rebelot/kanagawa.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'iceberg', 'background': 'dark',  'lightline': 'iceberg'})
call add(g:vimrc#colorschemes, {'name': 'iceberg', 'background': 'light', 'lightline': 'iceberg'})
'''

[[plugins]]
repo = 'savq/melange'

[[plugins]]
repo = '4513ECHO/vim-colors-hatsunemiku'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'gruvbox-material', 'background': 'dark', 'lightline': 'gruvbox_material'})
let g:gruvbox_material_enable_italic = 1
let g:gruvbox_material_spell_foreground = 'colored'
let g:gruvbox_material_diagnostic_text_highlight = 1
let g:gruvbox_material_diagnostic_line_highlight = 1
let g:gruvbox_material_diagnostic_virtual_text = 'colored'
let g:gruvbox_material_better_performance = 1

'''

[[plugins]]
repo = 'ishan9299/nvim-solarized-lua'
if = 'has("nvim")'

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'edge', 'background': 'dark', 'lightline': 'edge'})
let g:edge_better_performance = 1
'''

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'everforest', 'background': 'dark', 'lightline': 'everforest'})
call add(g:vimrc#colorschemes, {'name': 'everforest', 'background': 'light', 'lightline': 'everforest'})
let g:everforest_background = 'soft'
let g:everforest_sign_column_background = 'none'
let g:everforest_show_eob = 1
let g:everforest_diagnostic_text_highlight = 1
let g:everforest_diagnostic_line_highlight = 1
let g:everforest_diagnostic_virtual_text = 'colored'
let g:everforest_better_performance = 1
'''

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = '''
call add(g:vimrc#colorschemes, {'name': 'sonokai', 'background': 'dark', 'lightline': 'sonokai'})
let g:sonokai_style = 'espresso'
let g:sonokai_better_performance = 1
let g:sonokai_diagnostic_line_highlight = 1
let g:sonokai_diagnostic_text_highlight = 1
let g:sonokai_diagnostic_virtual_text = 'colored'
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = 'nvim-web-devicons'
if = 'has("nvim")'
lazy = true
#on_event = 'VimEnter'
hook_source = '''
call vimrc#set_random_colorschme()
lua require('lualine').setup()
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
#if = '!has("nvim")'
hook_add = '''
call vimrc#lightline#setup()
'''
