[[plugins]]
repo = 'rebelot/kanagawa.nvim'
if = 'has("nvim")'
hook_add = '''
call add(g:colorschemes, {'name': 'kanagawa'})
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:colorschemes, {'name': 'iceberg', 'background': 'dark'})
call add(g:colorschemes, {'name': 'iceberg', 'background': 'light'})
'''

[[plugins]]
repo = 'savq/melange'

[[plugins]]
repo = '4513ECHO/vim-colors-hatsunemiku'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
call add(g:colorschemes, {'name': 'gruvbox-material', 'background': 'dark'})
'''

[[plugins]]
repo = 'ishan9299/nvim-solarized-lua'
if = 'has("nvim")'
hook_add = '''
call add(g:colorschemes, {'name': 'solarized', 'background': 'dark'})
call add(g:colorschemes, {'name': 'solarized', 'background': 'light'})
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
set background=dark
colorscheme gruvbox-material

let g:lightline = {
  \ 'active': {
  \   'left':  [ [ 'mode', 'paste' ],
  \              [ 'readonly', 'filename', 'modified' ] ],
  \   'right': [ [ 'lineinfo' ],
  \              [ 'percent' ],
  \              [ 'fileformat', 'fileencofing', 'filetype' ] ] },
  \ 'inactive': {
  \   'left':  [ [ 'filename' ] ],
  \   'right': [ [ 'lineinfo' ],
  \              [ 'percent' ] ] },
  \ 'tabline': {
  \   'left':  [ [ 'gitbranch', 'tabs' ] ],
  \   'right': [ [ 'close' ] ] },
  \ 'separator': {
  \   'left': '',
  \   'right': '' },
  \ 'subseparator': {
  \   'left': '',
  \   'right': '' },
  \ 'colorscheme': 'gruvbox_material',
  \ 'component_function': {
  \   'gitbranch': 'gitbranch#name' },
  \ }
'''
