[[plugins]]
if = 'has("nvim")'
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
set background=dark
colorscheme iceberg
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
if = 'has("nvim")'
hook_add = '''
lua << EOF
require('lualine').setup()
EOF
'''
