[[plugins]]
repo = 'rebelot/kanagawa.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:colorschemes, {'name': 'iceberg', 'background': 'dark',  'lightline': 'iceberg'})
call add(g:colorschemes, {'name': 'iceberg', 'background': 'light', 'lightline': 'iceberg'})
'''

[[plugins]]
repo = 'savq/melange'

[[plugins]]
repo = '4513ECHO/vim-colors-hatsunemiku'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
call add(g:colorschemes, {'name': 'gruvbox-material', 'background': 'dark', 'lightline': 'gruvbox_material'})
'''

[[plugins]]
repo = 'ishan9299/nvim-solarized-lua'
if = 'has("nvim")'

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
call add(g:colorschemes, {'name': 'edge', 'background': 'dark', 'lightline': 'edge'})
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = 'nvim-web-devicons'
if = 'has("nvim")'
lazy = true
#on_event = 'VimEnter'
hook_source = '''
call init#set_random_colorschme()
lua require('lualine').setup()
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
#if = '!has("nvim")'
hook_add = '''
call vimrc#lightline#setup()
'''
