[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim', 'nvim-web-devicons']
on_cmd = 'Telescope'
hook_add = '''
function s:map_telescope_actions()
  nmap ;; <Cmd>Telescope<CR>
  nmap ;f <Cmd>Telescope find_files<CR>
  nmap ;g <Cmd>Telescope live_grep<CR>
  nmap ;b <Cmd>Telescope buffers<CR>
  nmap ;h <Cmd>Telescope help_tags<CR>
  nmap ;s <Cmd>Telescope treesitter<CR>
  nmap ;n <Cmd>Telescope resume<CR>
  nmap ;a <Cmd>Telescope git_status<CR>
endfunction

command MapTelescope call <SID>map_telescope_actions()
nmap <Leader>;t <Cmd>MapTelescope<CR>
'''
