[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = ''' source ~\AppData\Local\nvim\plugin\treesitter.lua '''

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'cocopon/iceberg.vim'
