[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = ''' execute 'source ' . g:config_dir . '/plugin/treesitter.lua' '''

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'rhysd/committia.vim'
hook_add = ''' execute 'source ' . g:config_dir . '/plugin/committia.vim' '''

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'neoclide/coc.nvim'

[[plugins]]
repo = 'ggandor/lightspeed.nvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'w0ng/vim-hybrid'
