[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = ''' execute 'source ' . g:config_dir . '/plugin/treesitter.lua' '''

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
	let g:hybrid_custom_term_colors = 1
	let g:hybrid_reduced_contrast = 1
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'rhysd/committia.vim'
hook_add = ''' execute 'source ' . g:config_dir . '/plugin/committia.vim' '''

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'ggandor/lightspeed.nvim'
hook_add = ''' execute 'source ' . g:config_dir . '/plugin/lightspeed.lua' '''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = ''' execute 'source ' . g:config_dir . '/plugin/telescope.vim' '''

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'hrsh7th/vim-searchx'
hook_add = ''' execute 'source ' . g:config_dir . '/plugin/searchx.vim' '''

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = ''' execute 'source ' . g:config_dir . '/plugin/ddc.vim' '''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/pum.vim'
hook_add = ''' execute 'source ' . g:config_dir . '/plugin/pum.vim' '''

[[plugins]]
repo = 'Shougo/ddc-cmdline'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'

