[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = """
call lexima#add_rule({'char': ']]', 'at': '\%#)', 'leave': 1})
call lexima#add_rule({'char': ']]', 'at': '\%#"', 'leave': 1})
call lexima#add_rule({'char': ']]', 'at': '\%#''', 'leave': 1})
call lexima#add_rule({'char': ']]', 'at': '\%#]', 'leave': 1})
call lexima#add_rule({'char': ']]', 'at': '\%#}', 'leave': 1})
"""

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
merged = 0
hook_source = '''
set helplang=ja,en
'''

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'airblade/vim-gitgutter'
