[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = """
call lexima#add_rule({'char': ']]', 'at': '\%#)', 'leave': 1})
call lexima#add_rule({'char': ']]', 'at': '\%#"', 'leave': 1})
call lexima#add_rule({'char': ']]', 'at': '\%#''', 'leave': 1})
call lexima#add_rule({'char': ']]', 'at': '\%#]', 'leave': 1})
call lexima#add_rule({'char': ']]', 'at': '\%#}', 'leave': 1})
"""

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1
au ColorScheme * hi Normal ctermbg=none
au ColorScheme * hi MatchParen cterm=bold ctermfg=214 ctermbg=black
au ColorScheme * hi SpellBad ctermfg=23 cterm=none ctermbg=none
set background=dark
colorscheme hybrid
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
merged = 0

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'hrsh7th/vim-searchx'
hook_add = '''
nnoremap / <Cmd>call searchx#start({ 'dir': 1 })<CR>
xnoremap / <Cmd>call searchx#start({ 'dir': 1 })<CR>

let g:searchx = {}

let g:searchx.auto_accept = v:true

let g:searchx.scrolloff = &scrolloff

let g:searchx.scrolltime = 500

let g:searchx.markers = split('ABCDEFGHIJKLMNOPQRSTUVWXYZ', '.\zs')

function g:searchx.convert(input) abort
    if a:input !~# '\k'
        return '\V' .. a:input
    endif
    return join(split(a:input, ' '), '.\{-}')
endfunction
'''

[[plugins]]
repo = 'ggandor/lightspeed.nvim'
if = 'has("nvim")'
hook_source = '''
lua << EOF
require'lightspeed'.setup {
    ignore_case = true,
}
EOF
'''

#[[plugins]]
#repo = 'chriskempson/vim-tomorrow-theme'
#
#[[plugins]]
#repo = 'cocopon/iceberg.vim'
