[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_source = '''
lua << EOF
local nightfox = require('nightfox')
nightfox.setup({
    fox = "nordfox",
    transparent = true,
    styles = {
        comments = "italic",
        keywords = "bold",
        functions = "italic,bold"
    },
    inverse = {
        match_paren = true,
    },
    colors = {
        red = "#FF000",
        bg_alt = "#000000",
    },
    hlgroups = {
        TSPunctDelimiter = { fg = "${red}" },
        LspCodeLens = { bg = "#000000", style = "italic" },
    }
})
nightfox.load()
EOF
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

