[[plugins]]
repo = 'EdenEast/nightfox.nvim'
if = 'has("nvim")'
on_event = 'VimEnter'
hook_source = '''
lua << EOF
local nightfox = require('nightfox')
nightfox.setup({
    fox = "nordfox",
    transparent = true,
    styles = {
        comments = "italic",
        keywords = "bold",
        functions = "italic,bold"
    },
    inverse = {
        match_paren = true,
    },
    colors = {
        red = "#FF000",
        bg_alt = "#000000",
    },
    hlgroups = {
        TSPunctDelimiter = { fg = "${red}" },
        LspCodeLens = { bg = "#000000", style = "italic" },
    }
})
nightfox.load()
EOF
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
on_source = 'nightfox.nvim'
hook_add = '''
let g:lightline = {
    \ 'colorscheme': 'nightfox',
    \ 'active': {
    \   'left': [ [ 'mode',  'paste' ],
    \       [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'FugitiveHead'
    \ },
    \ }
'''

