const s:here = fnamemodify(expand('<sfile>'), ':h')
execute printf('source %s', s:here . '/init.vim')
set background=dark
colorscheme gruvbox-material
let g:lightline.colorscheme = 'gruvbox_material'
